### ISSUE TITLE
Program breaks after finding match for vehicle

### ISSUE THREAD

**Issue by jSantiago318** [scrudden/transitime-docker#8]
Hello, 
This is everything I have done.
1.  cloned reop
2. Implemented Traccar configuration to the necessary files. I can see the vehicle in real-time, no noticeable latency in-vehicle refresh. 
3. Enable vehicle auto-assigner
4. I can see when 2 or more routes are a match and none is selected. (Program keeps running)
5. When one route is selected and is a temporary match the program breaks

**Comment by jSantiago318** [comment]
`For agencyId=1 Exception null for avlReport=AvlReport [vehicleId=1697, time=07-22-2020 10:44:54.000 AST, timeProcessed=07-22-2020 10:44:55.212 AST, location=[#####, #######], speed=NaN, heading=NaN, source=This is th, assignmentId=null, assignmentType=UNSET].
java.lang.NullPointerException: null
	at org.transitclock.core.RealTimeSchedAdhProcessor.generateEffectiveScheduleDifference(RealTimeSchedAdhProcessor.java:185) ~[Core.jar:na]
	at org.transitclock.core.PredictionGeneratorDefaultImpl.generate(PredictionGeneratorDefaultImpl.java:423) ~[Core.jar:na]
	at org.transitclock.core.MatchProcessor.processPredictions(MatchProcessor.java:80) ~[Core.jar:na]
	at org.transitclock.core.MatchProcessor.generateResultsOfMatch(MatchProcessor.java:200) ~[Core.jar:na]
	at org.transitclock.core.AvlProcessor.lowLevelProcessAvlReport(AvlProcessor.java:1425) ~[Core.jar:na]
	at org.transitclock.core.AvlProcessor.processAvlReport(AvlProcessor.java:1619) ~[Core.jar:na]
	at org.transitclock.avl.AvlClient.run(AvlClient.java:163) ~[Core.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_262]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_262]
	at org.transitclock.utils.threading.NamedThread.run(NamedThread.java:100) [Core.jar:na]`
